# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160328_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team',
            new_name='project',
        ),
    ]
