# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160328_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
