# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160328_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
