# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160329_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='abstract_en',
            field=models.TextField(max_length=200),
        ),
    ]
