# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160418_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='Title',
        ),
    ]
