# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160418_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='major',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Codigo',
        ),
        migrations.AddField(
            model_name='user',
            name='Correo',
            field=models.EmailField(default='a@a.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Nombres',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
