# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20160418_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Codigo',
            field=models.IntegerField(),
        ),
    ]
