# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20160418_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='Imagen',
        ),
    ]
