# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20160419_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Programa',
            field=models.CharField(choices=[('CIVIL', 'Ingenier\xeda civil'), ('ELECTRICA', 'Ingenier\xeda el\xe9ctrica'), ('ELECTRONICA', 'Ingenier\xeda electr\xf3nica'), ('INDUSTRIAL', 'Ingenier\xeda industrial'), ('MECANICA', 'Ingenier\xeda mec\xe1nica'), ('SISTEMAS', 'Ingenier\xeda de Sistemas')], default='CVL', max_length=255),
        ),
    ]
