# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20160429_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Abstract',
            field=models.TextField(max_length=2015),
        ),
        migrations.AlterField(
            model_name='project',
            name='Resumen',
            field=models.TextField(max_length=2015),
        ),
    ]
